AppBundle\Entity\Cycle:
    type: entity
    table: cycle
    repositoryClass: AppBundle\Repository\CycleRepository
    gedmo:
        translation:
            locale: locale
    oneToMany:
        sets:
            targetEntity: Set
            orderBy: {'position':'ASC'}
            mappedBy: cycle
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: 1024
            nullable: false
            gedmo:
                - translatable
        position:
            type: smallint
            nullable: false
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
        dateRelease:
            type: date
            nullable: true
            column: date_release
    uniqueConstraints:
        cycle_code_idx:
            columns: [ code ]
