AppBundle\Entity\Format:
    type: entity
    table: format
    repositoryClass: AppBundle\Repository\FormatRepository
    gedmo:
        translation:
            locale: locale
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: 255
            nullable: false
            gedmo:
                - translatable
        data:
            type: json_array
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
    uniqueConstraints:
        format_code_idx:
            columns: [ code ]
