AppBundle\Entity\Subtype:
    type: entity
    table: subtype
    repositoryClass: AppBundle\Repository\SubtypeRepository
    gedmo:
        translation:
            locale: locale
    manyToMany:
        cards:
            targetEntity: Card
            mappedBy: subtypes
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: 1024
            nullable: false
            gedmo:
                - translatable
    uniqueConstraints:
        subtype_code_idx:
            columns: [ code ]
            